In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('data/ex1data2.txt')
df_test = pd.read_csv('data/ex1data3.txt')
df.columns = ['house_size', 'bedrooms','house_price']
df_test.columns = ['house_size', 'bedrooms','house_price']

In [3]:
# ax = sns.scatterplot(data=df, x='house_size', y='bedrooms', z='house_price')   
# ax.set(xlabel='Population of City in 10,000s', ylabel='Profit in $10,000s', title='Scatter plot of training data')

In [4]:
n = df.shape[0]
X = np.hstack((np.ones((n, 1)), df.house_size.values.reshape(n, 1), df.bedrooms.values.reshape(n, 1)))
Y = df.house_price.values.reshape(n,1)

X_test = 
Y_test = 


iterations = 1500
alpha = 0.1

In [5]:


X_norm = X.copy() #.astype(float)  # make sure it's float
mu = X_norm.mean(axis=0)
sigma = X_norm.std(axis=0)

# avoid division by zero
sigma[sigma == 0] = 1  

X = (X_norm - mu) / sigma

[[ 0.00000000e+00 -5.01457678e-01 -2.28664780e-01]
 [ 0.00000000e+00  5.05397546e-01 -2.28664780e-01]
 [ 0.00000000e+00 -7.33034380e-01 -1.54348727e+00]
 [ 0.00000000e+00  1.26053896e+00  1.08615771e+00]
 [ 0.00000000e+00 -1.69086013e-02  1.08615771e+00]
 [ 0.00000000e+00 -5.84523234e-01 -2.28664780e-01]
 [ 0.00000000e+00 -7.19190120e-01 -2.28664780e-01]
 [ 0.00000000e+00 -7.78342865e-01 -2.28664780e-01]
 [ 0.00000000e+00 -6.34865995e-01 -2.28664780e-01]
 [ 0.00000000e+00 -7.35442077e-02  1.08615771e+00]
 [ 0.00000000e+00  1.96993413e-03 -2.28664780e-01]
 [ 0.00000000e+00 -1.36472659e-01 -2.28664780e-01]
 [ 0.00000000e+00  3.12070399e+00  2.40098019e+00]
 [ 0.00000000e+00 -9.19302596e-01 -2.28664780e-01]
 [ 0.00000000e+00  3.79540643e-01  1.08615771e+00]
 [ 0.00000000e+00 -8.53857006e-01 -1.54348727e+00]
 [ 0.00000000e+00 -9.59576805e-01 -2.28664780e-01]
 [ 0.00000000e+00  7.68438474e-01  1.08615771e+00]
 [ 0.00000000e+00  1.29955460e+00  1.08615771e+00]
 [ 0.00000000e+00 -2.91276650e-

In [6]:
def compute_cost(X, Y, theta):
    n = X.shape[0]           # the shape of X and shape of theta: n x 2 and 2 x 1 --> h must have shape n x 1 
    h = X.dot(theta)
    J = ((1/2*n) * np.sum((h-Y) **2))
    return J

In [7]:
def gradient_descent(X, Y):
    n = X.shape[0]
    theta = np.zeros((X.shape[1],1))
    
    for i in range(0, iterations):
        h = X.dot(theta)
        diff_hy = h - Y 
        delta = (1/n) * (diff_hy.T.dot(X))
        theta = theta - (alpha * delta.T)
    
    return theta

# DELTA IS JUST WEIGHING THE THINGS, it is basically the version of the sum part in our algorithm (dot product = sum of all products and later, we divide by the number (multiplying with alpha divided by n) so delta is just the weighed sum before we calculate the average error and correct it using alpha and subtracting from theta) 

In [8]:
theta = gradient_descent(X,Y)

#ax = sns.scatterplot(x='population', y='profit', data=df)
#plt.plot(X[:,1], X.dot(theta), color='r')
#ax.set(xlabel='Population of City in 10,000s', ylabel='Profit in $10,000s', title='Training data with linear regression fit');

In [9]:
results =  final_test_data.dot(theta)
print(results)

[[ 0.         -0.24974387 -0.22866478]]
[[-26110.27380807]]
